AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Stack for PDF upload and processing with two Lambda functions'

Parameters:
  StageName:
    Type: String
    Default: 'prod'
    Description: 'API Gateway stage name'

Resources:
  # Dependencies Layer
  DependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: rag-dependencies
      Description: Dependencies for RAG (PyMuPDF, google-generativeai, pinecone-client)
      ContentUri: ../.aws-sam/layers/
      CompatibleRuntimes:
        - python3.12
      RetentionPolicy: Retain

  UtilityLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: utility-layer
      Description: Common utility functions layer
      ContentUri: ../src/shared/
      CompatibleRuntimes:
        - python3.12
      RetentionPolicy: Retain

  # S3 Bucket for PDFs
  UploadBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaLogging
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sts:AssumeRole
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - secretsmanager:GetSecretValue              
                Resource:
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*'
                  - !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:PINECONE_DEV_KEY*'
                  - !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:GEMINI_DEV_KEY*'

  # Processor Lambda Function
  ProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: pdf_to_text.lambda_handler
      Runtime: python3.12
      CodeUri: ../src/Processor/
      Layers:
        - !Ref DependenciesLayer
        - !Ref UtilityLayer
      MemorySize: 512
      Timeout: 60
      Role: !GetAtt LambdaRole.Arn
      Policies:
        - PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:DeleteObject
                Resource: !Sub 'arn:${AWS::Partition}:s3:::${UploadBucket}/*'

  # Inference Lambda Function
  InferenceFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: inference.lambda_handler
      Runtime: python3.12
      CodeUri: ../src/Inference/
      Layers:
        - !Ref DependenciesLayer
        - !Ref UtilityLayer
      MemorySize: 256
      Timeout: 30
      Environment:
        Variables:
          LOG_LEVEL: info 
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /inference
            Method: post
      Role: !GetAtt LambdaRole.Arn

Outputs:
  InferenceEndpoint:
    Description: 'API Gateway endpoint URL for inference'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/inference'
